Address long-path issues on Windows

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24,8 +24,27 @@ set -u
 
 wd="$PWD"
 
-export TMPDIR="$wd/tmp/"
-mkdir -p "$TMPDIR"
+set +u
+if [ -z "$HICTKR_TMPDIR" ]; then
+  HICTKR_TMPDIR="$wd/tmp/"
+fi
+set -u
+
+TMPDIR="$HICTKR_TMPDIR"
+
+export HICTKR_TMPDIR
+export TMPDIR
+
+if [ -d "$TMPDIR" ]; then
+  # shellcheck disable=SC2064
+  trap "cd '$PWD'" EXIT
+else
+  # shellcheck disable=SC2064
+  trap "rm -rf '$TMPDIR' && cd '$PWD'" EXIT
+  mkdir "$TMPDIR"
+fi
+
+1>&2 echo "TMPDIR='$TMPDIR'"
 
 UV_VERSION='0.8.5'
 export UV_INSTALLER_URL="https://astral.sh/uv/$UV_VERSION/install.sh"
@@ -40,28 +59,15 @@ export UV_NO_MODIFY_PATH=1
 export VIRTUAL_ENV="$TMPDIR/venv/"
 
 
-# shellcheck disable=SC2064
-trap "rm -rf '$TMPDIR' && cd '$PWD'" EXIT
-
-set +u
-if [ -n "$R_HOME" ]; then
-  Rscript="$R_HOME/bin/Rscript"
+if command -v curl >/dev/null 2>&1; then
+  curl -L "$UV_INSTALLER_URL" -o "$UV_INSTALLER_DEST"
+elif command -v wget >/dev/null 2>&1; then
+  wget -O "$UV_INSTALLER_DEST" "$UV_INSTALLER_URL"
 else
-  Rscript="$(which Rscript)"
+  1>&2 echo "Unable to download file using curl or wget"
+  1>&2 echo "Please install either tools an try again"
+  exit 1
 fi
-set -u
-
-cat << EOF > "$TMPDIR/download-uv.R"
-#!/usr/bin/env Rscript
-
-download.file(
-  Sys.getenv("UV_INSTALLER_URL"),
-  dest=Sys.getenv("UV_INSTALLER_DEST"),
-  mode="wb"
-)
-EOF
-
-"$Rscript" "$TMPDIR/download-uv.R"
 
 if command -v sha256sum >/dev/null 2>&1; then
   checksum="$(sha256sum "$UV_INSTALLER_DEST")"
@@ -75,9 +81,10 @@ else
   checksum="$UV_INSTALLER_SHA256"
 fi
 
-checksum="$(echo "$checksum" | cut -f 1 -d ' ')"
+checksum="$(echo "$checksum" | tr -d \\ 2>/dev/null |  cut -f 1 -d ' ')"
 if [ "$checksum" != "$UV_INSTALLER_SHA256" ]; then
   1>&2 echo "FAILURE: Checksum verification for uv's install script failed!"
+  1>&2 echo "Expected $UV_INSTALLER_SHA256, found $checksum"
   exit 1
 fi
 
@@ -102,13 +109,15 @@ else
   exit 1
 fi
 
-which conan
-conan --version
-
 set +u
 if [ -z "$HICTKR_CONAN_HOME" ]; then
-  export HICTKR_CONAN_HOME="$wd/conan-staging/.conan2"
+  export HICTKR_CONAN_HOME="$TMPDIR/.conan2"
 fi
 set -u
+
+export CONAN_HOME="$HICTKR_CONAN_HOME"
+
+which conan
+conan --version
 
 python "$(dirname "$0")/deps/generate_makevars.py" --no-venv --workdir "$(dirname "$0")"
